// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbadaulprorpffonyzog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiYWRhdWxwcm9ycGZmb255em9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDczMzMsImV4cCI6MjA3Mzg4MzMzM30._N1TdcLq_o0-1zWGnE_mpohVfR6rrFP-_RgI1oc5ws4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});